export const RECORDS_REQUESTED = "RECORDS_REQUESTED"

export const RECORDS_REQUEST_SUCESS = "RECORDS_REQUEST_SUCESS"
export const RECORDS_REQUEST_FAILED = "RECORDS_REQUEST_FAILED"

export const LOADER_REMOVED = "LOADER_REMOVED"
export const LOADER_SHOWN = "LOADER_SHOWN"

export const QUERY_SEARCHED = "QUERY_SEARCHED"
export const EDIT_HANDLED = "EDIT_HANDLED"
export const DELETE_HANDLED = "DELETE_HANDLED"
export const CONFIRMATION_HANDLED = "CONFIRMATION_HANDLED"


